### ISSUE TITLE
请问论文中提到的智能异步调度，会将任务划分成细小的块，请问这部分的代码有吗？

### ISSUE THREAD

**Issue by a-seeker** [thu-pacman/FasterMoE#1]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by laekov** [comment]
在 [这份代码](https://github.com/thu-pacman/FasterMoE/blob/master/cuda/fused_compute.cuh)

**Comment by laekov** [comment]
This repository is being archived, and this issue is being closed.

In fact, it has been used as the artifact of the ppopp'22 paper only. 

Please move to the [repository of FastMoE](/laekov/fastmoe) for further discussion.
