### ISSUE TITLE
Support finetuning huggingface version of Switch Transformer

### ISSUE THREAD

**Issue by FranxYao** [thu-pacman/FasterMoE#2]
[Switch Transformer](https://arxiv.org/abs/2101.03961) is probably the only MoE architecture that currently has [open-source](https://github.com/google-research/t5x/blob/main/docs/models.md) pretrained checkpoints. 

Recent work shows that MoE like SwitchTransfomer has extremely huge potential for scaling and [instruction finetuning](https://arxiv.org/abs/2305.14705). Actually, after instruction finetuning, MoE architectures like SwitchTransformers strictly outperform their compute-matching dense counterparts. 

Huggingface Transformers is the most popular transformers library. However, their implementation of SwitchTransformers is very vanilla and does not support MP well. 

It would be awesome that FasterMoE could support SwitchTransformer. I believe this feature will make a huge impact in the large language model community.

**Comment by laekov** [comment]
This repository is being archived, and this issue is being closed.

In fact, it has been used as the artifact of the ppopp'22 paper only. 

Please move to the [repository of FastMoE](/laekov/fastmoe) for further discussion.
