### ISSUE TITLE
比较好奇这个仓库在千卡集群上，dense 20b，16 expert top2 的情况下，mfu 能到多少

### ISSUE THREAD

**Issue by kunpeng199494** [thu-pacman/FasterMoE#3]
比较好奇这个仓库在千卡集群上，dense 20b，16 expert top2 的情况下，mfu 能到多少

**Comment by laekov** [comment]
This repository is being archived, and this issue is being closed.

In fact, it has been used as the artifact of the ppopp'22 paper only. 

Please move to the [repository of FastMoE](/laekov/fastmoe) for further discussion.
